//started
/*
OOP is used to slove the real time problem. the same method not sutable for 
slove all the problem. every problem have diffrent character to slove it 
that why OOP coming to solve the real time problem  

for example:
    student 
    car
    etc

*/

// Class 

/*

class is a user define data type 
class are the blue print for a problem 


for example:
if we want to store a username in our program we use string 

what if the person have characterstick has to store in diffrenet varible 
so we createa a data structure use class to store the employee

*/

// #include "iostream"
// using std::string;
// class Student{
// public:
//     string name;
//     string department;
//     string phone_no;


//     void display(){
//         std::cout<<"Name :"<<name<<std::endl;
//         std::cout<<"Department : "<<department<<std::endl;
//         std::cout<<"Phone Number : "<<phone_no<<std::endl;
//     }

// };

// int main(){
//     Student student1;
//     student1.name = "VIshnu";
//     student1.department = "MAC";
//     student1.phone_no = "8608703560";
//     // std::cout<<student1.name;
//     student1.display();
//     return 1;
// }

// all of the class memeber defualtly private 


/*
Acess Modifer

1. Private means whate every decalre inside the class it beglong to that only 

2. publuc means we can use it any where on the program

3. protected means it in betweeen the above two 
*/

/* 
Constructor 
it is special type of method that will invoke object of class 

Default COnstructor :
it is Constructor the program automatical generated by the complier 
*/

// #include "iostream"
// using std::string;
// class Student{
// public:
//     string Name;
//     string Department;
//     string Phone_No;
//     int CGPA,Age;


//     void display(){
//         std::cout<<"Name :"<<Name<<std::endl;
//         std::cout<<"Department : "<<Department<<std::endl;
//         std::cout<<"Phone Number : "<<Phone_No<<std::endl;
//         std::cout<<"Phone No : "<<Phone_No<<std::endl;
//         std::cout<<"Age : "<<Age<<std::endl;
//     }
//     Student(string name, string department,string phone_no, int cgpa,int age){
//         Name = name;
//         Department = department;
//         Phone_No = phone_no;
//         CGPA = CGPA;
//         Age = age;

//     }

// };

// int main(){
//     Student student1 = Student("Vishnu","MCA","8608703560",55,22);
//     student1.display();


//     Student student2 = Student("Prakash","MBA","86087035660",11,22);
//     student2.display();
//     return 1;
// }


/*
Encapsulation:
it is bundling a data 
we don't allow all the class to use the properies of my class so i need to
encapsulation to store the data save
*/


#include "iostream"
using std::string;
class Student{
private:
    string Name;
    string Department;
    string Phone_No;
    int CGPA,Age;


public:
    void setName(string name){
        Name = name;
    }

    string getName(){
        return Name;
    }
    
    void display(){
        std::cout<<"Name :"<<Name<<std::endl;
        std::cout<<"Department : "<<Department<<std::endl;
        std::cout<<"Phone Number : "<<Phone_No<<std::endl;
        std::cout<<"Phone No : "<<Phone_No<<std::endl;
        std::cout<<"Age : "<<Age<<std::endl;
    }
    Student(string name, string department,string phone_no, int cgpa,int age){
        Name = name;
        Department = department;
        Phone_No = phone_no;
        CGPA = CGPA;
        Age = age;

    }

};

int main(){
    Student student1 = Student("Vishnu","MCA","8608703560",55,22);
    // student1.display();


    Student student2 = Student("Prakash","MBA","86087035660",11,22);
    // student2.display();

    // std::cout<<student2.Name<<std::endl;
    std::cout<<student2.getName()<<std::endl;
    student2.setName("CJ");
    std::cout<<student2.getName()<<std::endl;
    return 1;
}